name: flutter_spinbox
description: >-
  SpinBox is a numeric input widget with an input field for entering a specific value,
  and spin buttons for quick, convenient, and accurate value adjustments.
version: 0.3.1+1
homepage: https://github.com/jpnurmi/flutter_spinbox
repository: https://github.com/jpnurmi/flutter_spinbox
issue_tracker: https://github.com/jpnurmi/flutter_spinbox/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  intl: ^0.16.1
  meta: ^1.2.4

dev_dependencies:
  effective_dart: ^1.2.4
  flutter_test:
    sdk: flutter
  flutter_test_ui: ^1.0.0
